### ISSUE TITLE
Translate website elements

### ISSUE THREAD

**Issue by Rogzy-DB** [DecouvreBitcoin/sovereign-university-data#147]
The new version of the university requires a thorough review. We are using Crowdin for this. The text being translated is primarily the main content of the platform, such as buttons, headers, footers, static titles, etc.

https://crowdin.com/translate/the-sovereign-academy/all/en-it?filter=basic&value=0

**Comment by Asi0Flammeus** [comment]
Hey I saw on the Crowdin Dashboard that the IT translation is at 62%. 
Would you translate/review the rest of it, so I can close this issue?

**Comment by Asi0Flammeus** [comment]
It is far from a dead project! But we can definitively do better in terms of follow-up. 
That's why I'm here ;-) 

I had a look about these French expressions in the Crowding, and it seems that there's only 5 of them which I would translate in English as (I speak French):  

1. Se connecter = log in
2. Identifiant contributeur = Contributor ID
3. Connectez vous ! = Log in! 
4. Envoyer un lien = Send a link 
5. Etude des hyperinflations = Hyperinflation investigation

So you can translate them in Italian!

![Image](https://github.com/DecouvreBitcoin/sovereign-university-data/assets/90136504/24c87e52-e8c6-4a47-aab5-d266a0556895)
